### ISSUE TITLE
Odstranit tlačítko na Google Podcasts

### ISSUE THREAD

**Issue by honzajavorek** [juniorguru/junior.guru#1259]
## Proč

Google oznámil, že [Google Podcasts přestanou existovat](https://blog.youtube/news-and-events/podcast-destination-on-youtube-music/), respektive sloučí se s YouTube Music. Aktuálně je na několika místech na webu sada tlačítek:

![Screenshot 2023-11-21 at 15-51-00 Podcast o programování a kariéře v IT](https://github.com/juniorguru/junior.guru/assets/283441/98dbc535-f94d-4309-9d66-35196ba2bf95)

Přijde mi, že tlačítko na Google Podcasts už je zbytečné a šlo by jej odstranit.

## Jak

- Kód webových stránek a v podstatě všeho na junior.guru se nachází v tzv. repozitáři, tady na GitHubu: https://github.com/juniorguru/junior.guru Je veřejný ke čtení (open source) a jde procházet klikáním i tady na webu. I nějaké úpravy by šlo dělat přes web, ale protože to bude úprava na více místech, už by to trochu drhlo. Bude lepší to udělat z počítače přes Git.
- Co je Git a jak funguje GitHub [vysvětluje asi nejlíp yablko tady na YouTube](https://www.youtube.com/watch?v=0v5K4GvK4Gs).
- Nejdřív bude potřeba mít nainstalovaný Git a mít účet na GitHubu.
- Potom přes Git stáhnout („naklonovat“) obsah repozitáře https://github.com/juniorguru/junior.guru na svůj disk.
- Potom použít nějaký editor (např. [VS Code](https://code.visualstudio.com/)) a najít kód, který souvisí s tlačítkem.
- Tlačítko je určitě někde v souboru `podcast.md`, což je sice tzv. [Markdown](https://www.markdownguide.org/), ale jsou do něj naházené i značky HTML a jsou tam i nějaké značky šablonovacího jazyka [Jinja](https://jinja.palletsprojects.com). Není potřeba to všechno umět, stačí v tom guláši najít tlačítko (odkaz) na Google Podcasts a smazat ho.
- Stejné tlačítko (se stejnými HTML class třídami) je určitě ještě i někde jinde. Mělo by být možné najít všechna taková přes funkci, která dokáže najít text napříč všemi soubory v projektu. Tu má každý lepší editor.
- Ještě tam někde bude CSS, nebo spíš [SCSS](https://sass-lang.com/documentation/syntax/), což je akorát trochu vylepšené CSS, které obsahuje pravidlo přímo pro toto tlačítko, aby bylo googlovsky modré. To se taky může smazat.
- V ideálním světě by šlo projekt spustit a ověřit, že je vše správně smazané, ale můj projekt je bohužel zamotaná bestie, kterou nebudeme lokálně rozjíždět, to by bylo na dlouho. Takže se spokojíme s tím, že změny jsou hotové a budeme doufat.
- Když jsou změny hotové, uloží se do Gitu („commitnou“ se) a pak se vytvoří tzv. Pull Request na repozitáři, kterým se pošle návrh na změnu.
- Já uvidím tenhle návrh na změnu (přijde mi mailem, že vznikl Pull Request). Mrknu na to a když to bude OK, tak změnu přijmu, ono se to pošle na „produkci“.
- Jakmile doběhnou všechny věci na tzv. Continuous Integration serveru (rád dodatečně vysvětlím), tak se to samo nahodí a výsledek by měl jít vidět na junior.guru
- Pokud se mi něco nebude líbit (všimnu si zapomenuté závorky nebo něco), můžu psát komentáře a poprosit o změny. Pokud to nastane, bude potřeba přidat do Pull Requestu další commity. Až změny přijmu, platí předchozí bod.

## Kde hledat pomoc

- S GitHub účtem lze komunikovat tady pod issue, přidávat komentáře. Ideálně komunikujme tady.
- Budu se snažit být co nejvíc k ruce.
- Klub je taky k dispozici.
- [ChatGPT](https://chat.openai.com/) může leccos napovědět, když se člověk [dobře zeptá](https://www.youtube.com/watch?v=twpwcfL590Y).
- Neexistuje hloupý dotaz. Určitě je dobré nejdřív něco zkusit, ale pak je lepší se včas zeptat, než být tři dny zaseknutý na nějaké věci.
- Všechny nejasné a prapodivné pojmy se pokusím objasnit.

**Comment by KristynaHel** [comment]
Musela jsem vytvořit fork, protože při pull request z VS code se nedělo vůbec nic, nebo to hodilo error. V desktop aplikaci GitHub to mám uncommited changes, ale na webu vidím, že mám fork ready k pull request. Ale netuším jak je ten fork vidět z vaší strany. Až mi budete psát feedback, můžete mi poslat i screenshot, toho jak vidíte ten request ode mne? Docela mě to zajímá :)

**Comment by honzajavorek** [comment]
Nedošlo mi, že když vám nedám oprávnění (což nebyl záměr, jen mi to nedošlo), tak nemůžete snadno přispívat přímo tady. Ale vyřešila jste to skvěle! Je to vlastně celkem běžná praxe, že se postupuje takto:

1. Někde je open source repozitář, do kterého chci přispět, ale nejsem v týmu lidí, kteří se o něj starají.
2. Udělám si tedy _fork_, kopii někde u sebe. GitHub na to má přímo tlačítko. Kopie pak bude na mém profilu, což je v pohodě. Na rozdíl od původního kódu (tzv. _upstream_), se můj _fork_ zastavil v čase a obsahuje moje změny.

![Screenshot 2023-11-27 at 10-09-27 KristynaHel_junior guru The junior guru website Discord bot and synchronization scripts](https://github.com/juniorguru/junior.guru/assets/283441/d22188f7-702b-4397-a989-e2648c766213)

Tady vidím, že máte na svém profilu _fork_ kódu junior.guru, a že ten kód tam má jeden commit navíc a je tři commity pozadu oproti _upstream_ verzi kódu. Tedy forknula jste, pak jste přidala svou jednu změnu, a mezitím já jsem přidal nějaké tři změny na svém původním repozitáři. Zvýrazním, kde to tam čtu:

![Screenshot 2023-11-27 at 10-09-27 KristynaHel_junior guru The junior guru website Discord bot and synchronization scripts](https://github.com/juniorguru/junior.guru/assets/283441/aa54df16-b013-4284-af17-b97e6aa7536e)

3. Pak se dá z toho forku (mojí kopie) poslat Pull Request (žádost o změny) na upstream (původní kód). To se povedlo tady: https://github.com/juniorguru/junior.guru/pull/1262 Přišlo mi to krásně do mailu a hezky vidím provedené změny.

![Screenshot 2023-11-27 at 10-09-32 Google podcast button by KristynaHel · Pull Request #1262 · juniorguru_junior guru](https://github.com/juniorguru/junior.guru/assets/283441/4f50a10c-6f4c-47c9-95fa-556e268f85e8)

![Screenshot 2023-11-27 at 10-16-14 Google podcast button by KristynaHel · Pull Request #1262 · juniorguru_junior guru](https://github.com/juniorguru/junior.guru/assets/283441/c406a2c9-bbee-4b36-a7b6-0b83a0b7cd79)

4. Já se mám teď na změny podívat a pokud je přijmu, budou pod vaším jménem začleněny. „Bohužel“ nemám co bych vytknul, takže si asi nevyzkoušíme žádné „tam a zpátky“ 😄 Nezbývá mi než to schválit, přijmout, a poslat na produkci.

**Comment by honzajavorek** [comment]
Udělal jsem review:

![Screenshot 2023-11-27 at 10-23-34 Google podcast button by KristynaHel · Pull Request #1262 · juniorguru_junior guru](https://github.com/juniorguru/junior.guru/assets/283441/3de8ac6b-d2f3-4d51-b4b6-68de6f7fe23a)

Pak jsem už jen zmáčkl na Merge tlačítko a změny byly začleněny. Teď se spustí tzv. _build_ [tady na CircleCI](https://app.circleci.com/pipelines/github/juniorguru/junior.guru/9188/workflows/521494c5-3ee8-4ea6-b8db-f3295bd7b843). a jakmile doběhne, měly by se změny projevit přímo na webu.

Build dělá a kontroluje spoustu věcí a protože to nemám udělané ideálně, tak trvá dlouho a může lidově řečeno „spadnout“ z různých důvodů. V ideálním světě by build spoustěl jen pár testů, trval pár sekund nebo minut, a to, jestli projde nebo spadne, by záviselo zcela na tom, zda je váš kód správný nebo ne 😄

**Comment by honzajavorek** [comment]
@KristynaHel Kolik nám zbývá hodin? Chceme zkusit ještě něco?

**Comment by KristynaHel** [comment]
Supr! To video mělo asi 1,5 h, samotná práce zabrala asi hoďku (nejhorší bylo pochopit jak funguje ten git a github). Každopádně stáž musí být ukončena do konce listopadu, a od zítra do pátku jsem v práci do večera. Takže pokud by to byla nějaká práce, kterou můžu udělat později, nebo ji dělat s žáky (třeba ty data), tak by to bylo asi lepší :)
Bylo by něco takového? Nebo máte jiný nápad?

**Comment by honzajavorek** [comment]
Jestli do konce listopadu už nic nestihneme, tak to neřešme. Pokud se do toho dá zpětně započítat i něco, co by se udělalo potom, tak klidně. Napadlo mě, že můžeme někde - klidně i jen cvičně - vyzkoušet, jak by vypadalo, kdyby se mi změny nelíbily.

Nevím, jak moc zostra jdete na žáky s programováním, ale sdílení kódu přes Git je v praxi prakticky všude a je to brána (především skrze GitHub) k podílení se na pestrém světě open source apod. Dovedu si představit, že pokud by měli žáci pracovat na něčem v týmu, tak si musí nějak sdílet soubory a řešit konflikty, pokud editují stejné řádky, a přesně k tomu Git je, tak snad bude tahle exkurze k něčemu trochu užitečná :)

Co se týče dalších nápadů, třeba těch dat, které by šly dělat i mimo stáž, můžu se určitě zamyslet a něco nadhodit. Nejjednodušší by asi bylo začít někam odlévat data o pracovních nabídkách. Pokud máte zájem, můžu na to pak sepsat separátní issue.

**Comment by KristynaHel** [comment]
Přes ten Github Desktop to jde i docela jednoduše, ale je to spíš pro starší žáky (kvinta). Pro mladší žáky to moc není, přeci jen je to humanitní gymnázium a programování tady nikoho moc netáhne :)  (kromě HTML, to jim nevadí, protože to není programování)
Jinak ta data pořád vidím jako fajn nápad, ale když jsem koukala na ten discord, tak bych možná i nějakým způsobem nechala žáky sledovat jaké dovednosti a znalosti vyžadují na konkrétních pozicích. Třeba často vidím, že je zájem o Java a SQL, bylo by fajn vytvořit nějaký žebříček nejvíce žádoucích dovedností.
Pokud už nechcete ty data řešit, tak já bych nechala žáky zpracovat ty požadované dovednosti. 
Ale pokud to nebude nic náročného a nezabere vám to moc času, tak ty data o pracovních nabídkách určitě využijeme :)

+ vám musím poslat nějaké formuláře týkající se stáže, chcete to poslat sem anebo do mailu?

**Comment by honzajavorek** [comment]
Formuláře do mailu, data zkusím připravit :)
