### ISSUE TITLE
missing https redirect

### ISSUE THREAD

**Issue by landsman** [juniorguru/junior.guru#1431]
Nevim, kde najdu repo s infra, ale vsiml jsem si absence redirectu na HTTPS.
Stranky funguji na http, viz: http://junior.guru

Asi nejlepsi reseni, je to cely soupnout za [cloudflare](https://www.cloudflare.com/en-gb/), staci free varianta :)

**Comment by honzajavorek** [comment]
Díky! Tohoto jsem si nevšiml! Cloudflare není potřeba, ani repo s infra, celé junior.guru jede na GitHub Pages jako statická stránka 😄 Stačilo zaškrtnout tohle, vůbec nevím, proč to zaškrtnuté nebylo a myslel jsem, že to zaškrtnuté mám.

<img width="791" alt="Screenshot 2024-08-16 at 11 39 20" src="https://github.com/user-attachments/assets/311c7edb-6ddd-4f63-9f23-2465a0e13ce3">
